# Generated by Django 6.0.2 on 2026-02-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='LINE ID'),
        ),
    ]
