# Generated by Django 6.0.2 on 2026-02-25 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登入時間')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP位址')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='裝置資訊')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '登入紀錄',
                'verbose_name_plural': '登入紀錄',
                'ordering': ['-login_time'],
            },
        ),
    ]
