# Generated by Django 6.0.2 on 2026-02-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userloginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginrecord',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='登入地點'),
        ),
    ]
