# Generated by Django 6.0.2 on 2026-02-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_promotions',
            field=models.BooleanField(default=True, verbose_name='接受優惠通知'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_month_day',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出生月日'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '男性'), ('F', '女性'), ('O', '保密')], default='O', max_length=1, verbose_name='稱謂'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='暱稱'),
        ),
    ]
