# Generated by Django 6.0.2 on 2026-02-26 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_accept_promotions_user_birth_month_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='例如：公司、住家、公婆家', max_length=50, null=True, verbose_name='地址標籤')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='收件人姓名')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='收件人聯絡電話')),
                ('city', models.CharField(max_length=20, verbose_name='縣市')),
                ('district', models.CharField(max_length=20, verbose_name='鄉鎮市區')),
                ('detail_address', models.CharField(max_length=255, verbose_name='詳細地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='設為預設收件地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='所屬會員')),
            ],
            options={
                'verbose_name': '收件地址',
                'verbose_name_plural': '會員地址簿',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
