# Generated by Django 6.0.2 on 2026-02-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品種名稱')),
                ('color', models.CharField(max_length=50, verbose_name='顏色')),
                ('description', models.TextField(blank=True, verbose_name='品種介紹')),
            ],
        ),
    ]
