# Generated by Django 6.0.2 on 2026-02-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名稱')),
                ('price', models.PositiveIntegerField(verbose_name='價格')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存數量')),
                ('is_mixed', models.BooleanField(default=False, verbose_name='是否為混合禮盒')),
                ('description', models.TextField(blank=True, verbose_name='商品文案')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='商品圖片')),
                ('varieties', models.ManyToManyField(related_name='products', to='store.variety', verbose_name='包含品種')),
            ],
        ),
    ]
