# Generated by Django 6.0.2 on 2026-02-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有貨'),
        ),
    ]
