# Generated by Django 6.0.2 on 2026-02-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=20, verbose_name='左上角標籤'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('catty', '台斤'), ('bunch', '串'), ('box', '盒'), ('kg', '公斤')], default='box', max_length=10, verbose_name='計量單位'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_value',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5, verbose_name='規格數值'),
        ),
    ]
