# Generated by Django 6.0.2 on 2026-02-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_badge_product_unit_type_product_unit_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('catty', '台斤'), ('bunch', '串')], default='catty', max_length=10, verbose_name='計量單位'),
        ),
    ]
