# Generated by Django 6.0.2 on 2026-02-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productimage_options_productimage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mix_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='混合口味上限'),
        ),
    ]
