# Generated by Django 6.0.2 on 2026-02-10 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_mix_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='等級名稱')),
                ('price', models.IntegerField(verbose_name='價格')),
                ('stock', models.IntegerField(default=0, verbose_name='庫存')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='store.product', verbose_name='所屬商品')),
            ],
            options={
                'verbose_name': '商品規格/等級',
                'verbose_name_plural': '商品規格/等級',
                'ordering': ['price'],
            },
        ),
    ]
