# Generated by Django 6.0.2 on 2026-02-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgrade',
            options={'ordering': ['-price'], 'verbose_name': '商品規格/等級', 'verbose_name_plural': '商品規格/等級'},
        ),
    ]
