# Generated by Django 6.0.2 on 2026-03-02 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_productgrade_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='訂單編號')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='收件人姓名')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='收件人電話')),
                ('shipping_city', models.CharField(max_length=20, verbose_name='收件縣市')),
                ('shipping_district', models.CharField(max_length=20, verbose_name='收件鄉鎮市區')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='收件詳細地址')),
                ('subtotal', models.PositiveIntegerField(verbose_name='商品小計')),
                ('shipping_fee', models.PositiveIntegerField(default=0, verbose_name='運費')),
                ('total_amount', models.PositiveIntegerField(verbose_name='訂單總金額')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('shipping', '出貨中'), ('delivered', '已送達'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='訂單狀態')),
                ('payment_method', models.CharField(choices=[('cod', '貨到付款'), ('transfer', '銀行轉帳')], default='cod', max_length=20, verbose_name='付款方式')),
                ('payment_status', models.CharField(choices=[('unpaid', '未付款'), ('paid', '已付款')], default='unpaid', max_length=20, verbose_name='付款狀態')),
                ('note', models.TextField(blank=True, verbose_name='訂單備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下單時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='訂購會員')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名稱快照')),
                ('grade_name', models.CharField(blank=True, max_length=50, verbose_name='等級名稱快照')),
                ('variety_names', models.CharField(blank=True, max_length=255, verbose_name='品種名稱快照')),
                ('product_image', models.URLField(blank=True, max_length=500, verbose_name='商品圖片URL快照')),
                ('unit_price', models.PositiveIntegerField(verbose_name='單價')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('item_total', models.PositiveIntegerField(verbose_name='品項小計')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='所屬訂單')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '訂單品項',
                'verbose_name_plural': '訂單品項',
            },
        ),
    ]
