# Generated by Django 6.0.2 on 2026-03-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', '貨到付款'), ('transfer', '銀行轉帳'), ('credit_card', '信用卡付款')], default='cod', max_length=20, verbose_name='付款方式'),
        ),
    ]
