# Generated by Django 6.0.2 on 2026-03-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待付款'), ('pending_shipment', '待出貨'), ('shipped', '待收貨'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending_payment', max_length=20, verbose_name='訂單狀態'),
        ),
    ]
