# Generated by Django 6.0.2 on 2026-03-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='付款嘗試次數'),
        ),
    ]
