# Generated by Django 6.0.2 on 2026-03-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_payment_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='優惠碼')),
                ('title', models.CharField(max_length=100, verbose_name='優惠名稱')),
                ('discount_type', models.CharField(choices=[('fixed', '固定金額折抵'), ('percent', '百分比折扣'), ('free_shipping', '免運費')], max_length=20, verbose_name='折扣類型')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折扣數值')),
                ('min_spend', models.PositiveIntegerField(default=0, verbose_name='最低消費門檻')),
                ('valid_from', models.DateTimeField(verbose_name='生效時間')),
                ('valid_to', models.DateTimeField(verbose_name='失效時間')),
                ('usage_limit', models.PositiveIntegerField(default=0, verbose_name='總共可使用次數 (0表無限)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次數')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '優惠券',
                'verbose_name_plural': '優惠券管理',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='使用的優惠碼'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='優惠折抵金額'),
        ),
    ]
