# Generated by Django 6.0.2 on 2026-03-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_usercoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='公告標題')),
                ('content', models.TextField(verbose_name='公告內容')),
                ('is_active', models.BooleanField(default=True, help_text='取消勾選會在前台隱藏', verbose_name='是否啟用')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='數字越大越排在前面', verbose_name='排序權重')),
                ('start_date', models.DateTimeField(blank=True, help_text='留空表示即刻顯示', null=True, verbose_name='開始顯示時間')),
                ('end_date', models.DateTimeField(blank=True, help_text='留空表示永久顯示', null=True, verbose_name='結束顯示時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '網站公告',
                'verbose_name_plural': '網站公告管理',
                'ordering': ['-sort_order', '-created_at'],
            },
        ),
    ]
