# Generated by Django 6.0.3 on 2026-03-04 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_bulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分類名稱')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='數字越大越排在前面', verbose_name='排序權重')),
            ],
            options={
                'verbose_name': '消息分類',
                'verbose_name_plural': '消息分類管理',
                'ordering': ['-sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('summary', models.CharField(blank=True, help_text='列表頁顯示的簡短說明', max_length=300, verbose_name='摘要文字')),
                ('content', models.TextField(verbose_name='詳細內容')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='封面圖片')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否發佈')),
                ('published_date', models.DateField(verbose_name='發佈日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='store.newscategory', verbose_name='分類')),
            ],
            options={
                'verbose_name': '最新消息',
                'verbose_name_plural': '最新消息管理',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
