# Generated by Django 6.0.3 on 2026-03-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_newscategory_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_pinned', '-published_date', '-created_at'], 'verbose_name': '最新消息', 'verbose_name_plural': '最新消息管理'},
        ),
        migrations.AddField(
            model_name='news',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='勾選後會置頂在列表最上方', verbose_name='是否置頂'),
        ),
    ]
