# Generated by Django 6.0.3 on 2026-03-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_news_options_news_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variety',
            options={'ordering': ['-sort_order', 'id'], 'verbose_name': '葡萄品種', 'verbose_name_plural': '葡萄品種管理'},
        ),
        migrations.AddField(
            model_name='variety',
            name='flavor',
            field=models.CharField(blank=True, help_text='例如：甜度高、帶有玫瑰香氣', max_length=200, verbose_name='風味特色'),
        ),
        migrations.AddField(
            model_name='variety',
            name='image',
            field=models.ImageField(blank=True, help_text='品種介紹頁用的大圖', null=True, upload_to='variety_images/', verbose_name='品種圖片'),
        ),
        migrations.AddField(
            model_name='variety',
            name='origin',
            field=models.CharField(blank=True, help_text='例如：日本岡山、台灣彰化', max_length=100, verbose_name='產地/來源'),
        ),
        migrations.AddField(
            model_name='variety',
            name='season',
            field=models.CharField(blank=True, help_text='例如：6~8月', max_length=50, verbose_name='產季'),
        ),
        migrations.AddField(
            model_name='variety',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='數字越大越排在前面', verbose_name='排序權重'),
        ),
    ]
