# Generated by Django 6.0.3 on 2026-03-05 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_variety_options_variety_flavor_variety_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DessertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dessert_images/', verbose_name='分類封面圖')),
                ('description', models.TextField(blank=True, verbose_name='分類簡介')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='數字越大越排在前面', verbose_name='排序權重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '甜點分類',
                'verbose_name_plural': '甜點分類管理',
                'ordering': ['-sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：草莓大福', max_length=100, verbose_name='品項名稱')),
                ('flavor', models.CharField(help_text='例如：草莓', max_length=50, verbose_name='口味')),
                ('price', models.PositiveIntegerField(verbose_name='售價')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dessert_images/', verbose_name='品項圖片')),
                ('description', models.TextField(blank=True, verbose_name='品項介紹')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存數量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='數字越大越排在前面', verbose_name='排序權重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desserts', to='store.dessertcategory', verbose_name='所屬分類')),
            ],
            options={
                'verbose_name': '甜點品項',
                'verbose_name_plural': '甜點品項管理',
                'ordering': ['-sort_order', 'id'],
            },
        ),
    ]
