# Generated by Django 6.0.3 on 2026-03-05 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_dessertcategory_dessert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='數字越大越排在前面', verbose_name='排序權重')),
                ('is_active', models.BooleanField(default=True, help_text='關閉後前台分類Tab不會出現', verbose_name='是否顯示')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類管理',
                'ordering': ['-sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.productcategory', verbose_name='商品分類'),
        ),
    ]
