# Generated by Django 6.0.3 on 2026-03-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_productcategory_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '葡萄禮盒', 'verbose_name_plural': '葡萄禮盒管理'},
        ),
    ]
