# Generated by Django 6.0.3 on 2026-03-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['-sort_order', '-created_at'], 'verbose_name': '首頁快訊', 'verbose_name_plural': '首頁快訊管理'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-sort_order', 'id'], 'verbose_name': '葡萄禮盒分類', 'verbose_name_plural': '葡萄禮盒分類管理'},
        ),
        migrations.CreateModel(
            name='DessertGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：6顆裝', max_length=50, verbose_name='規格名稱')),
                ('count', models.PositiveIntegerField(default=1, help_text='如果是6顆裝就填6', verbose_name='數量(顆)')),
                ('price', models.IntegerField(verbose_name='價格(整盒)')),
                ('stock', models.IntegerField(default=0, verbose_name='此規格庫存(盒)')),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='store.dessert', verbose_name='所屬甜點')),
            ],
            options={
                'verbose_name': '甜點規格',
                'verbose_name_plural': '甜點規格管理',
                'ordering': ['price'],
            },
        ),
    ]
