# Generated by Django 6.0.3 on 2026-03-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_bulletin_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DessertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dessert_gallery/', verbose_name='甜點圖片')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.dessert', verbose_name='所屬甜點')),
            ],
            options={
                'verbose_name': '甜點更多圖片',
                'ordering': ['order'],
            },
        ),
    ]
