# Generated by Django 6.0.3 on 2026-03-09 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_dessertimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.dessert', verbose_name='甜點商品'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(default='product', max_length=20, verbose_name='品項分類'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='葡萄商品'),
        ),
    ]
