# Generated by Django 6.0.2 on 2026-03-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_orderitem_dessert_orderitem_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='大標題')),
                ('subtitle', models.TextField(blank=True, verbose_name='副標題/內文')),
                ('image', models.ImageField(help_text='建議尺寸: 1400x600', upload_to='banners/', verbose_name='電腦版圖片')),
                ('mobile_image', models.ImageField(blank=True, help_text='若無則自動縮放電腦版圖片。建議尺寸: 800x800', null=True, upload_to='banners/', verbose_name='手機版圖片 (選填)')),
                ('link_url', models.URLField(blank=True, help_text='例如: /product/1 或 https://...', verbose_name='點擊後跳轉網址')),
                ('order', models.IntegerField(default=0, help_text='數字越小排越前面', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '首頁輪播圖',
                'verbose_name_plural': '首頁輪播圖',
                'ordering': ['order', '-id'],
            },
        ),
    ]
