# Generated by Django 6.0.3 on 2026-03-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='custom_link',
            field=models.CharField(blank=True, help_text='如果您想連結到外部網頁 (如 FB 或 Line) 或其他頁面，請在此填寫 (例如: https://...)', max_length=500, verbose_name='自訂跳轉網址'),
        ),
        migrations.AddField(
            model_name='banner',
            name='target_dessert',
            field=models.ForeignKey(blank=True, help_text='若選擇，點擊圖片會自動跳轉到此甄點商品', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.dessert', verbose_name='推薦甄點商品'),
        ),
        migrations.AddField(
            model_name='banner',
            name='target_product',
            field=models.ForeignKey(blank=True, help_text='若選擇，點擊圖片會自動跳轉到此商品', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='推薦一般商品'),
        ),
    ]
