# Generated by Django 6.0.3 on 2026-03-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_banner_link_url_banner_custom_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='唯一代號，前端用此代號取得圖片 (例如: friendly_01, promo_tart, hero_banner)', max_length=50, unique=True, verbose_name='圖片代號')),
                ('label', models.CharField(help_text='方便辨識的中文說明', max_length=100, verbose_name='說明')),
                ('group', models.CharField(choices=[('promo', '廣告橫幅'), ('friendly', '安心農產'), ('media', '底部媒體展示'), ('hero', '頂部橫幅背景'), ('other', '其他')], default='other', max_length=20, verbose_name='群組分類')),
                ('image', models.ImageField(upload_to='site_images/', verbose_name='圖片')),
                ('alt_text', models.CharField(blank=True, help_text='圖片的 alt 說明文字', max_length=100, verbose_name='替代文字 (SEO)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '網站素材',
                'verbose_name_plural': '網站素材庫',
                'ordering': ['group', 'key'],
            },
        ),
    ]
