# Generated by Django 6.0.3 on 2026-03-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_siteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='description',
            field=models.TextField(blank=True, help_text='若此素材需要搭配說明文字，請在此填寫', verbose_name='介紹文字 (選填)'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='title',
            field=models.CharField(blank=True, help_text='若此素材需要搭配標題文字，請在此填寫', max_length=100, verbose_name='標題 (選填)'),
        ),
    ]
