# Generated by Django 6.0.3 on 2026-03-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_siteimage_description_siteimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='link_url',
            field=models.CharField(blank=True, help_text='點擊此圖片時要跳轉的頁面 (例如: /products 或 https://line.me/...)', max_length=500, verbose_name='跳轉連結 (選填)'),
        ),
    ]
