# Generated by Django 6.0.3 on 2026-03-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_siteimage_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteimage',
            name='link_url',
        ),
        migrations.AddField(
            model_name='siteimage',
            name='custom_link',
            field=models.CharField(blank=True, help_text='若要跳轉到外部網頁 (如 LINE、FB) 或其他頁面，請在此填寫 (例如: https://...)', max_length=500, verbose_name='自訂跳轉網址'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='link_page',
            field=models.CharField(blank=True, choices=[('', '不跳轉'), ('/products', '商品頁'), ('/desserts', '甜點頁'), ('/news', '最新消息'), ('/varieties', '品種介紹')], default='', help_text='從下拉選單選擇要跳轉的站內頁面', max_length=50, verbose_name='跳轉到站內頁面'),
        ),
    ]
