# Generated by Django 6.0.3 on 2026-03-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_siteimage_link_url_siteimage_custom_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='target_dessert',
            field=models.ForeignKey(blank=True, help_text='選擇後，點擊圖片會跳轉到此甄點商品頁面', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.dessert', verbose_name='② 推薦甄點商品'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='target_product',
            field=models.ForeignKey(blank=True, help_text='選擇後，點擊圖片會跳轉到此商品頁面', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='① 推薦一般商品'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='custom_link',
            field=models.CharField(blank=True, help_text='若要跳轉到外部網頁 (如 LINE、FB) 或其他頁面，請在此填寫 (例如: https://...)', max_length=500, verbose_name='④ 自訂跳轉網址'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='link_page',
            field=models.CharField(blank=True, choices=[('', '不跳轉'), ('/products', '商品頁'), ('/desserts', '甜點頁'), ('/news', '最新消息'), ('/varieties', '品種介紹')], default='', help_text='從下拉選單選擇要跳轉的站內頁面', max_length=50, verbose_name='③ 跳轉到站內頁面'),
        ),
    ]
