# Generated by Django 6.0.3 on 2026-03-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_siteimage_target_dessert_siteimage_target_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='group',
            field=models.CharField(choices=[('top_banner', '頂部優惠橫幅'), ('promo', '廣告橫幅'), ('friendly', '安心農產'), ('media', '底部媒體展示'), ('hero', '頂部橫幅背景'), ('other', '其他')], default='other', max_length=20, verbose_name='群組分類'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='圖片 (選填)'),
        ),
    ]
